# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: suliveevil
brief-intro: Coder, Life is Short, Use Python!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://suliveevil.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: suliveevil
facebook_username: suliveevil
github_username:  suliveevil
email: suliveevil@gmail.com
# weibo_username: 
zhihu_username: suliveevil
# linkedIn_username: suliveevil
# dribbble_username:

description_footer: 代码改变世界，努力改变人生！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 # short_name
# duoshuo_shortname: #hygblog
# disqus_shortname: suliveevil

# comments-gitalk
# comments: true
comments:
  gitalk: false
  gitalk_clientID: '你刚刚注册一个oauth application的clientID'
  gitalk_Secret: 'oauth application的secret'
  gitalk_repo: '用户名.github.io或者是一个存放评论的仓库'
  gitalk_owner: 'github用户名'
  gitalk_admin: 'github用户名'
  distractionFreeMode: false


# 网站统计
leancloud: 
  enable: true
  app_id: e78I2g4eazNHG3wSRYGu2rQv-gzGzoHsz
  app_key: acFYrqrwoePfrNudHcfLbFUI

# statistic analysis 统计
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: c4d8c3a27450c10490331c50c7c7beb1
google_analytics_id: UA-132357502-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: 
  - jekyll-paginate
  - jekyll-mermaid
paginate: 9
 
